config/routes.rb
Rails.application.routes.draw do
  
  get 'queries' => 'queries#index'
  get 'queries/new'
  post 'queries/create'
  get 'queries/:id' => 'queries#show'
  get 'databases/new'
  post 'databases/create'
  get 'users/:id/setadmin' => 'users#invert_admin'
  get 'queries/select_star/:table' => 'queries#select_star'
  get 'set_database/:db_id' => 'users#set_database'
  get 'query/:id/rollback' => 'queries#rollback'
  resources :db_grants
  resources :users
  resources :table_grants

  root to: "home#index"

  get 'home/index'
  

  get 'tables' => 'tables#index'
  post 'tables/set_database'

  devise_for :users, :path_prefix => 'auth'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :grants
  has_many :queries
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  before_action :set_user, only: [:show, :edit, :update, :destroy]


	before_filter :ensure_admin!, except: [:set_database]
	

	

  respond_to :html
	def create
		@user = User.new(user_params)
		@user.save
		@users = User.all
		render 'users/new'
	end

	def new
		@users = User.all
		@user= User.new
		@user.save
	end

	def index
		@users = User.all
	end
	def show
	end	

	def destroy
		@user.destroy
		redirect_to '/table_grants'
	end

	def edit
	end

	def set_database
    	current_user.db_id = params[:db_id]
    	current_user.save
    	redirect_to(:back)
    end

    def invert_admin
    	@user = User.find(params[:id])
    	@user.admin = (not @user.admin)
    	@user.save
    	redirect_to(:back)
    end
	private
	def set_user
      @user = User.find(params[:id])
    end
	def user_params
		params.require(:user).permit(:email, :password, :db_id)
	end
	def ensure_admin!
		unless current_user && current_user.admin?
			redirect_to root_path, notice: "You are not admin"
			return false
		end
	end
end

app/views/users/_form.html.erb
<%= form_for :user, :url => {:controller => "users", :action => "create"},   :html => { :class => 'form-inline' } do |f| %>

	<div class="form-group">
		<%= f.text_field :email,  :class => "form-control input-sm", :placeholder => "Email" %>
	</div>
	<div class="form-group">

		<%= f.password_field :password, :class => "form-control input-sm", :placeholder => "password" %>
	</div>
	<div class="form-group">
		<%= f.submit "Add", :class =>"btn btn-default"%>
	</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<table>
	<tr>
		<th>
			Email
		</th>
		<th>
			admin
		</th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td>
			<%= user.email %>
		</td>
		<td>
			<%= user.admin %>
		</td>
		<td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %>
</table>

<p>
<%= link_to 'New User', new_user_path %> 
</p>

app/views/users/new.html.erb
<section class="content-header">
  <h1>Users </h1>
</section>

<section class="content">
  <div class = "row">
    <div class="col-md-12">


      <div class="box" style="min-height:200px">
        
          <div class="box-header">
            <div class="box-title"> <h3>New User</h3> </div>
          </div>
          <div class = "box-body">
            <%= render 'form' %>
          </div>
      </div>
      <div class="box"> <!-- First Box -->
        <div class="box-header">
          <div class="box-title"> <h3>Users</h3> </div>
        </div>
        <div class = "box-body">

        <table class = "table table-bordered table-striped dataTable">
            <thead>
              <th>User ID</th>
              <th>Email</th>
              <th>Admin</th>
              <th colspan="2"></th>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td> <%= user.id %></td>
                  <td> <%= user.email %> </td>
                  <td> <%= link_to "#{user.admin}", "users/#{user.id}/setadmin",
                    data: (user.id==current_user.id ? {confirm: 'Are you sure?'} : nil) %> </td>
                  <td> <%= link_to 'Edit', edit_user_path(user) %> </td>
                  <td> <%= link_to 'Remove', user,  method: :delete, data: {confirm: 'Are you sure?'} %> </td>
                </tr>
              <% end %>    
            </tbody>
          </table>
        </div>
      </div>

    </div>

    </div>

  </div>
</section>