config/routes.rb
Rails.application.routes.draw do
  
  get 'queries' => 'queries#index'
  get 'queries/new'
  post 'queries/create'
  get 'queries/:id' => 'queries#show'
  get 'databases/new'
  post 'databases/create'
  get 'users/:id/setadmin' => 'users#invert_admin'
  get 'queries/select_star/:table' => 'queries#select_star'
  get 'set_database/:db_id' => 'users#set_database'
  get 'query/:id/rollback' => 'queries#rollback'
  resources :db_grants
  resources :users
  resources :table_grants

  root to: "home#index"

  get 'home/index'
  

  get 'tables' => 'tables#index'
  post 'tables/set_database'

  devise_for :users, :path_prefix => 'auth'

end

app/models/table_grant.rb
class TableGrant < ActiveRecord::Base
	#associations
	belongs_to :user
	
	validate :table,  :presence => true
	#validations
	validate :user, :presence => true
	validate :user_id_exists, :table_exists, :db_id_exists
	validate :valid_access_type
	
	# after_initialize :init
	include ApplicationHelper
	def db_id_exists
		begin
			Database.find(self.db_id)
		rescue ActiveRecord::RecordNotFound
			errors.add(:db_id, "db_id foreign key most exists")
			false
		end
	end

	def user_id_exists
		begin
	  		User.find(self.user_id)
	 	rescue ActiveRecord::RecordNotFound
	  	    errors.add(:user_id, "user_id foreign key must exist")
		    false
		end
	end

	def table_exists
		t = get_all_tables
		if (t.detect {|f| f[1]==self.db_id && f[0] == self.table }).nil?
			errors.add(:table, "table foreign key must exist")
			false
		else
			true
		end
	end

	def valid_access_type
		if(self.access_type.nil? || self.access_type>15 || self.access_type < 1)
			errors.add(:access_type, "Access_type is not valid")
			false
		end
	end


	# cattr_accessor :current_db
	# cattr_accessor :current_tables
	



	# def init
	# 	self.current_db = PG::Connection.new(dbname: 'shop', user: 'postgres', password: '1234')
	# 	self.current_tables = current_db.exec("SELECT table_name FROM information_schema.tables where table_schema='public'")
	# end

end

app/controllers/table_grants_controller.rb
class TableGrantsController < AdminController

  before_action :set_table_grant, only: [:show, :edit, :update, :destroy]

  respond_to :html

  helper :all
  include ApplicationHelper

  def index
    @table_grants = TableGrant.all
    @table_grant = TableGrant.new
    @databases = Database.all
    @tables = get_all_tables
    @users = User.all
    @user = User.new
    respond_with(@table_grants)
  end

  def show
    respond_with(@table_grant)
  end

  def new
    @table_grant = TableGrant.new
    respond_with(@table_grant)
  end

  def edit
  end

  def create
    @table_grant = TableGrant.new(table_grant_params)
    last_tb = TableGrant.find_by(:user_id=>@table_grant.user_id, :db_id=>@table_grant.db_id, :table=>@table_grant.table)

    if !last_tb.nil? 
      if !@table_grant.access_type.nil?
        last_tb.access_type = last_tb.access_type | @table_grant.access_type
        last_tb.save
      end

      redirect_to table_grants_path
    else
      if  @table_grant.save
        redirect_to table_grants_path
      else
        @table_grants = TableGrant.all
        @tables = get_all_tables
        @databases = Database.all
        @users = User.all
        render :action => :index
      end
    end
  end

  def update
    @table_grant.update(table_grant_params)
    respond_with(@table_grant)
  end

  def destroy
    @table_grant.destroy
    respond_with(@table_grant)
  end





  private
    

    def set_table_grant
      @table_grant = TableGrant.find(params[:id])
    end

    def table_grant_params
      params.require(:table_grant).permit(:user_id, :db_id, :table, :access_type)
    end
end

app/helpers/table_grants_helper.rb
module TableGrantsHelper
end

app/views/table_grants/_form.html.erb
<% 
  def options_for_users
    u = [] 
    @users.all.each do |user|
      tmp = []
      tmp << user.email
      tmp << user.id
      u << tmp
    end
    u
  end
%>

<% 
  def options_for_database
    u = [] 
    Database.all.each do |db|
      tmp = []
      tmp << db.name
      tmp << db.id
      u << tmp
    end
    u
  end
%>
<%= form_for(@table_grant, :html => { :class => 'form-inline' }) do |f| %>
  <% if @table_grant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table_grant.errors.count, "error") %> prohibited this table_grant from being saved:</h2>

      <ul>
      <% @table_grant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.select :user_id, options_for_users, :selected => :value %>
  </div>

  <div class="form-group">
    <%= f.select :db_id, options_for_database ,:class => "form-control", :placeholder => "Database ID", :selected => :value %>
  </div>
  <div class="form-group">
    <%= f.select :table, [], :class => "form-control input-sm", :placeholder => "Table Name", :selectd => :value %>
  </div>
  <%= f.select(:access_type, [  ['SELECT',1],
                                ['INSERT',2],
                                ['UPDATE',4],
                                ['DELETE',8],
                                 ],{ :prompt => "Please select"},
                                   { :size => 4 , :class=>'form-control'}
                                 ) %>
  </div>

  <div class="form-group">
    <%= f.submit "Add", :class =>"btn btn-default" %>
  </div>
  <div class="form-group"> 

<% end %>


<script>


$(function() {
    $('#table_grant_db_id').change(function() {
      var x = document.getElementById("table_grant_db_id").value
      document.getElementById("table_grant_table").options.length = 0
      var hash = new Array()
      var i =0;

      <% @tables.each do |table| %>
        hash.push(['<%= table[0] %>', <%=table[1]%>]);
        i++
      <% end %>
      var j =0 
      for (i=0; i<hash.length; i++)
         if (hash[i][1] == x){
           document.getElementById("table_grant_table").options[j++]=new Option(hash[i][0], hash[i][0], true, false)
         }

    });
});

 
</script>

app/views/table_grants/edit.html.erb
<h1>Editing table_grant</h1>

<%= render 'form' %>

<%= link_to 'Show', @table_grant %> |
<%= link_to 'Back', table_grants_path %>

app/views/table_grants/index.html.erb
<section class="content-header">
  <h1>Table Grants </h1>
</section>

<section class="content">
  <div class = "row">
    <!-- <div class="col-md-6">


      <div class="box" style="min-height:200px">
        
          <div class="box-header">
            <div class="box-title"> <h3>New User</h3> </div>
          </div>
          <div class = "box-body">
            <%= render 'users/form' %>
          </div>
      </div>
      <div class="box"> 
        <div class="box-header">
          <div class="box-title"> <h3>Users</h3> </div>
        </div>
        <div class = "box-body">

        <table class = "table table-bordered table-striped dataTable">
            <thead>
              <th>User ID</th>
              <th>Email</th>
              <th>Admin</th>
              <th colspan="2"></th>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td> <%= user.id %></td>
                  <td> <%= user.email %> </td>
                  <td> <%= link_to "#{user.admin}", "users/#{user.id}/setadmin",
                    data: (user.id==current_user.id ? {confirm: 'Are you sure?'} : nil) %> </td>
                  <td> <%= link_to 'Edit', edit_user_path(user) %> </td>
                  <td> <%= link_to 'Remove', user,  method: :delete, data: {confirm: 'Are you sure?'} %> </td>
                </tr>
              <% end %>    
            </tbody>
          </table>
        </div>
      </div>
      <div class="box">
          <div class="box-title"> <h3>Table_names</h3> </div>
          <div class = "box-body">

          <table id="table1" class = "table table-bordered table-striped dataTable">
            <thead>
              <tr>
                <th>Table name</th>
                <td>Database ID </td>
              </tr>
            </thead>
            <tbody>
              <% @tables.each do |key,value| %>
              <tr>
                
               <td> <%= link_to key, "/queries/select_star/#{key}" %></td>
               <td> <%= value %> </td>
              </tr>
              <% end %>
            </tbody>
          </table>


        </div>
      </div>
    </div> -->
    <div class="col-md-12">

      <div class="box" style="min-height:200px">
          <div class="box-header">
            <div class="box-title"> <h3>New Grant</h3> </div>
          </div>
          <div class = "box-body">
             <span>SELECT = 1, INSERT = 2, DELETE = 4, UPDATE = 8</span>
            <%= render 'form' %>
          </div>
      </div>

      <div class="box">
        <div class="box-header">
          <div class="box-title"> <h3>Grants</h3> </div>
        </div>
        <div class = "box-body">
          <span>SELECT = 1, INSERT = 2, DELETE = 4, UPDATE = 8</span>
          <table id="table2" class = "table table-bordered table-striped dataTable">
            <thead>
              <tr>
                <th>User</th>
                <th>Db</th>
                <th>Table</th>
                <th>Type</th>
                <th colspan="2"></th>
              </tr>
            </thead>

            <tbody>
              <% @table_grants.each do |table_grant| %>
                <tr>
                  <td><%= User.find(table_grant.user_id).email %></td>
                  <td><%= Database.find(table_grant.db_id).name %></td>
                  <td><%= table_grant.table %></td>
                  <% hash = {1=>"SELECT", 2=>"INSERT", 4=>"DELETE", 8=>"UPDATE"} %>
                  <td>  <% hash.each do |key, value| %>
                          <% if key & table_grant.access_type >0 %>
                            <%= value + " "%>
                          <% end %>
                        <%end%>
                  </td>
                  <td><%= link_to 'Edit', edit_table_grant_path(table_grant) %></td>
                  <td><%= link_to 'Remove', table_grant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          
        </div>
      </div>
      <div class="box">

      </div>
    </div>

  </div>
</section>

<script>
  $(function () {
    $("#table1").DataTable();
    $("#table2").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });
  });
</script>

app/views/table_grants/new.html.erb
<h1>New table_grant</h1>

<%= render 'form' %>

<%= link_to 'Back', table_grants_path %>

app/views/table_grants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @table_grant.user_id %>
</p>

<p>
  <strong>Db:</strong>
  <%= @table_grant.db_id %>
</p>

<p>
  <strong>Table:</strong>
  <%= @table_grant.table %>
</p>

<p>
  <strong>Type:</strong>
  <%= @table_grant.access_type %>
</p>

<%= link_to 'Edit', edit_table_grant_path(@table_grant) %> |
<%= link_to 'Back', table_grants_path %>