config/routes.rb
Rails.application.routes.draw do
  
  get 'queries' => 'queries#index'
  get 'queries/new'
  post 'queries/create'
  get 'queries/:id' => 'queries#show'
  get 'databases/new'
  post 'databases/create'
  get 'users/:id/setadmin' => 'users#invert_admin'
  get 'queries/select_star/:table' => 'queries#select_star'
  get 'set_database/:db_id' => 'users#set_database'
  get 'query/:id/rollback' => 'queries#rollback'
  resources :db_grants
  resources :users
  resources :table_grants

  root to: "home#index"

  get 'home/index'
  

  get 'tables' => 'tables#index'
  post 'tables/set_database'

  devise_for :users, :path_prefix => 'auth'

end

app/models/db_grant.rb
class DbGrant < ActiveRecord::Base
	belongs_to :user
	validate :user, :presence => true
end

app/controllers/db_grants_controller.rb
class DbGrantsController < ApplicationController
  before_action :set_db_grant, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @db_grants = DbGrant.all
    respond_with(@db_grants)
  end

  def show
    respond_with(@db_grant)
  end

  def new
    @db_grant = DbGrant.new
    respond_with(@db_grant)
  end

  def edit
  end

  def create
    @db_grant = DbGrant.new(db_grant_params)
    @db_grant.save
    respond_with(@db_grant)
  end

  def update
    @db_grant.update(db_grant_params)
    respond_with(@db_grant)
  end

  def destroy
    @db_grant.destroy
    respond_with(@db_grant)
  end

  private
    def set_db_grant
      @db_grant = DbGrant.find(params[:id])
    end

    def db_grant_params
      params.require(:db_grant).permit(:user_id, :db, :access_type)
    end
end

app/helpers/db_grants_helper.rb
module DbGrantsHelper
end

app/views/db_grants/_form.html.erb
<%= form_for(@db_grant) do |f| %>
  <% if @db_grant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@db_grant.errors.count, "error") %> prohibited this db_grant from being saved:</h2>

      <ul>
      <% @db_grant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :db %><br>
    <%= f.text_field :db %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/db_grants/edit.html.erb
<h1>Editing db_grant</h1>

<%= render 'form' %>

<%= link_to 'Show', @db_grant %> |
<%= link_to 'Back', db_grants_path %>

app/views/db_grants/index.html.erb
<h1>Listing db_grants</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Db</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @db_grants.each do |db_grant| %>
      <tr>
        <td><%= db_grant.user_id %></td>
        <td><%= db_grant.db %></td>
        <td><%= db_grant.type %></td>
        <td><%= link_to 'Show', db_grant %></td>
        <td><%= link_to 'Edit', edit_db_grant_path(db_grant) %></td>
        <td><%= link_to 'Destroy', db_grant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Db grant', new_db_grant_path %>

app/views/db_grants/new.html.erb
<h1>New db_grant</h1>

<%= render 'form' %>

<%= link_to 'Back', db_grants_path %>

app/views/db_grants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @db_grant.user_id %>
</p>

<p>
  <strong>Db:</strong>
  <%= @db_grant.db %>
</p>

<p>
  <strong>Type:</strong>
  <%= @db_grant.type %>
</p>

<%= link_to 'Edit', edit_db_grant_path(@db_grant) %> |
<%= link_to 'Back', db_grants_path %>